use crate::editor::ToolType;

/// Events generated by UI components, primarily for internal UI state changes or simple editor updates.
#[derive(Debug, Clone)]
pub enum UIEvent {
    /// A tool was selected in the UI
    ToolSelected(Option<ToolType>),
    /// The tool size was changed
    ToolSizeChanged(f32),
    /// A color was selected in the UI
    ColorSelected(usize),
    /// Toggle debug panel
    ToggleDebugPanel,
    /// Toggle visual options panel
    ToggleVisualOptionsPanel,
    /// Show the new map dialog
    ShowNewMapDialog,
    /// Show the reset confirmation dialog
    ShowResetConfirmDialog,
    /// Toggle the top panel (retract/expand)
    ToggleTopPanel,
}

/// Events generated by the UI that require immediate action from the application core.
pub enum AppAction {
    TogglePause,
    RequestReset,
    RequestSaveMap(String),
    RequestLoadMap(String),
    RequestNewMap { width: u32, height: u32 },
    ToggleCameraLockOnSelectedAnt,
}
